version: "3.8"

services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:8080"
    depends_on:
      - app

  app:
    build: .
    container_name: node-mysql-docker
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules # volume anônimo

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
